# Generated by Django 5.2.6 on 2025-09-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=10)),
                ('curso', models.CharField(max_length=30)),
            ],
        ),
    ]
