# Generated by Django 5.2.6 on 2025-09-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id_livro', models.AutoField(primary_key=True, serialize=False)),
                ('nome_livro', models.CharField(max_length=60)),
                ('nome_autor', models.CharField(max_length=50)),
                ('codigo_livro', models.CharField(max_length=80)),
                ('numero_paginas', models.IntegerField()),
            ],
        ),
    ]
