# Generated by Django 5.2.6 on 2025-09-14 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_livro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id_leitura', models.AutoField(primary_key=True, serialize=False)),
                ('pagina_atual', models.IntegerField()),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.livro')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.IntegerField()),
                ('leitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.leitura')),
            ],
        ),
    ]
