# Generated by Django 5.2.6 on 2025-09-14 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_leitura_nota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leitura',
            old_name='livro',
            new_name='id_livro',
        ),
        migrations.RenameField(
            model_name='leitura',
            old_name='pessoa',
            new_name='id_pessoa',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='leitura',
            new_name='id_leitura',
        ),
    ]
