# Generated by Django 5.2.6 on 2025-09-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0004_rename_livro_leitura_id_livro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='matricula',
            field=models.CharField(default=2024101065, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(max_length=3),
        ),
    ]
