# Generated by Django 5.2.6 on 2025-09-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0005_pessoa_matricula_alter_pessoa_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='nota',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
