# Generated by Django 5.2.6 on 2025-09-14 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0006_alter_nota_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='id_leitura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.leitura', unique=True),
        ),
    ]
