# Generated by Django 5.2.6 on 2025-09-14 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0007_alter_nota_id_leitura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logado',
            fields=[
                ('id_login', models.AutoField(primary_key=True, serialize=False)),
                ('logado', models.BooleanField(choices=[(True, 'sim'), (False, 'não')])),
                ('id_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.pessoa', unique=True)),
            ],
        ),
    ]
