# Generated by Django 5.2.6 on 2025-09-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0008_logado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leitura',
            old_name='id_livro',
            new_name='livro',
        ),
        migrations.RenameField(
            model_name='leitura',
            old_name='id_pessoa',
            new_name='pessoa',
        ),
        migrations.RenameField(
            model_name='logado',
            old_name='id_pessoa',
            new_name='pessoa',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='id_leitura',
            new_name='leitura',
        ),
    ]
