# Generated by Django 5.2.6 on 2025-09-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0009_rename_id_livro_leitura_livro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='imagem',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
