# Generated by Django 5.2.6 on 2025-09-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0010_livro_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='matricula',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
