# Generated by Django 5.2.6 on 2025-09-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0011_alter_pessoa_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitura',
            name='nota',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
