# Generated by Django 5.2.6 on 2025-09-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0012_leitura_nota_delete_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='nome_autor',
            field=models.CharField(max_length=150),
        ),
    ]
