# Generated by Django 5.2.6 on 2025-09-18 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0013_alter_livro_nome_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='imagem',
        ),
    ]
