# Generated by Django 5.2.6 on 2025-09-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0014_remove_livro_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='codigo_livro',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
