# Generated by Django 5.2.6 on 2025-09-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0016_alter_livro_nome_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='nome_livro',
            field=models.CharField(max_length=250),
        ),
    ]
