# Generated by Django 5.2.6 on 2025-11-25 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0018_alter_livro_nome_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='numero_paginas',
        ),
    ]
