# Generated by Django 5.2.6 on 2025-11-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0019_remove_livro_numero_paginas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(max_length=5),
        ),
    ]
